/**
 * Lexical Editor Theme — Playground-style class mapping.
 * Styling is handled in globals.css, not via Tailwind utility classes here.
 */
import type { EditorThemeClasses } from "lexical";

const theme: EditorThemeClasses = {
 ltr: "ltr",
 rtl: "rtl",
 paragraph: "editor-paragraph",
 heading: {
  h1: "editor-heading-h1",
  h2: "editor-heading-h2",
  h3: "editor-heading-h3",
  h4: "editor-heading-h4",
  h5: "editor-heading-h5",
  h6: "editor-heading-h6",
 },
 list: {
  ul: "editor-list-ul",
  ol: "editor-list-ol",
  listitem: "editor-listitem",
  listitemChecked: "editor-listitem-checked",
  listitemUnchecked: "editor-listitem-unchecked",
  nested: {
   listitem: "editor-nested-listitem",
  },
 },
 quote: "editor-quote",
 code: "editor-code",
 codeHighlight: {
  atrule: "editor-tokenAttr",
  attr: "editor-tokenAttr",
  boolean: "editor-tokenProperty",
  builtin: "editor-tokenSelector",
  cdata: "editor-tokenComment",
  char: "editor-tokenSelector",
  class: "editor-tokenFunction",
  "class-name": "editor-tokenFunction",
  comment: "editor-tokenComment",
  constant: "editor-tokenProperty",
  deleted: "editor-tokenProperty",
  doctype: "editor-tokenComment",
  entity: "editor-tokenOperator",
  function: "editor-tokenFunction",
  important: "editor-tokenVariable",
  inserted: "editor-tokenSelector",
  keyword: "editor-tokenAttr",
  namespace: "editor-tokenVariable",
  number: "editor-tokenProperty",
  operator: "editor-tokenOperator",
  prolog: "editor-tokenComment",
  property: "editor-tokenProperty",
  punctuation: "editor-tokenPunctuation",
  regex: "editor-tokenVariable",
  selector: "editor-tokenSelector",
  string: "editor-tokenSelector",
  symbol: "editor-tokenProperty",
  tag: "editor-tokenProperty",
  url: "editor-tokenOperator",
  variable: "editor-tokenVariable",
 },
 text: {
  bold: "editor-text-bold",
  italic: "editor-text-italic",
  underline: "editor-text-underline",
  strikethrough: "editor-text-strikethrough",
  underlineStrikethrough: "editor-text-underlineStrikethrough",
  code: "editor-text-code",
  subscript: "editor-text-subscript",
  superscript: "editor-text-superscript",
 },
 link: "editor-link",
 indent: "editor-indent",
 table: "editor-table",
 tableCell: "editor-table-cell",
 tableCellHeader: "editor-table-cell-header",
 tableRow: "editor-table-row",
 tableAddColumns: "editor-table-add-columns",
 tableAddRows: "editor-table-add-rows",
 tableCellResizer: "editor-table-cell-resizer",
 tableCellSelected: "editor-table-cell-selected",
 tableSelected: "editor-table-selected",
};

export default theme;
