import { describe, expect, it } from "vitest";

import {
 formatDailyReadingCountdown,
 resolveDailyReadingReleaseState,
 shouldAutoCaptureDailyReading,
 shouldAutoGenerateDailyReading,
 vietnamDailyReadingDateKey,
} from "./daily-reading.scheduler";

describe("Daily Reading scheduler", () => {
 it("uses the Vietnam calendar date around UTC boundaries", () => {
  expect(vietnamDailyReadingDateKey(new Date("2026-08-17T17:30:00.000Z"))).toBe("2026-08-18");
 });

 it("preserves the legacy 10:00 default release", () => {
  const before = resolveDailyReadingReleaseState(new Date("2026-08-18T02:59:59.000Z"));
  const atRelease = resolveDailyReadingReleaseState(new Date("2026-08-18T03:00:00.000Z"));

  expect(before.dateKey).toBe("2026-08-18");
  expect(before.isDue).toBe(false);
  expect(before.remainingMilliseconds).toBe(1000);
  expect(atRelease.isDue).toBe(true);
  expect(atRelease.remainingMilliseconds).toBe(0);
  expect(atRelease.releaseAt.toISOString()).toBe("2026-08-18T03:00:00.000Z");
 });

 it("uses the configured local capture time", () => {
  const before = resolveDailyReadingReleaseState(new Date("2026-08-18T00:29:59.000Z"), {
   hour: 7,
   minute: 30,
  });
  const due = resolveDailyReadingReleaseState(new Date("2026-08-18T00:30:00.000Z"), {
   hour: 7,
   minute: 30,
  });

  expect(before.isDue).toBe(false);
  expect(due.isDue).toBe(true);
  expect(due.releaseAt.toISOString()).toBe("2026-08-18T00:30:00.000Z");
 });

 it("runs auto capture only when enabled, visible, due, and not already completed or blocked", () => {
  const ready = {
   autoCaptureEnabled: true,
   isVisible: true,
   releaseIsDue: true,
   hasScheduledArticle: false,
   hasBlockingAttempt: false,
  };

  expect(shouldAutoCaptureDailyReading(ready)).toBe(true);
  expect(shouldAutoCaptureDailyReading({ ...ready, autoCaptureEnabled: false })).toBe(false);
  expect(shouldAutoCaptureDailyReading({ ...ready, isVisible: false })).toBe(false);
  expect(shouldAutoCaptureDailyReading({ ...ready, releaseIsDue: false })).toBe(false);
  expect(shouldAutoCaptureDailyReading({ ...ready, hasScheduledArticle: true })).toBe(false);
  expect(shouldAutoCaptureDailyReading({ ...ready, hasBlockingAttempt: true })).toBe(false);
 });

 it("keeps the legacy generation decision wrapper compatible", () => {
  expect(
   shouldAutoGenerateDailyReading({
    autoGenerateEnabled: true,
    isVisible: true,
    releaseIsDue: true,
    hasScheduledReading: false,
    hasBlockingAttempt: false,
   }),
  ).toBe(true);
 });

 it("formats the remaining release time without dropping a partial minute", () => {
  expect(formatDailyReadingCountdown(3_600_001)).toBe("01:01");
  expect(formatDailyReadingCountdown(0)).toBe("00:00");
 });
});
