import { describe, expect, it } from "vitest";

import {
 formatDailyReadingCountdown,
 resolveDailyReadingReleaseState,
 shouldAutoGenerateDailyReading,
 vietnamDailyReadingDateKey,
} from "./daily-reading.scheduler";

describe("Daily Reading scheduler", () => {
 it("uses the Vietnam calendar date around UTC boundaries", () => {
  expect(vietnamDailyReadingDateKey(new Date("2026-08-17T17:30:00.000Z"))).toBe("2026-08-18");
 });

 it("becomes due at 10:00 Asia/Ho_Chi_Minh", () => {
  const before = resolveDailyReadingReleaseState(new Date("2026-08-18T02:59:59.000Z"));
  const atRelease = resolveDailyReadingReleaseState(new Date("2026-08-18T03:00:00.000Z"));

  expect(before.dateKey).toBe("2026-08-18");
  expect(before.isDue).toBe(false);
  expect(before.remainingMilliseconds).toBe(1000);
  expect(atRelease.isDue).toBe(true);
  expect(atRelease.remainingMilliseconds).toBe(0);
  expect(atRelease.releaseAt.toISOString()).toBe("2026-08-18T03:00:00.000Z");
 });

 it("runs auto generation only when enabled, visible, due, and not already blocked", () => {
  const ready = {
   autoGenerateEnabled: true,
   isVisible: true,
   releaseIsDue: true,
   hasScheduledReading: false,
   hasBlockingAttempt: false,
  };

  expect(shouldAutoGenerateDailyReading(ready)).toBe(true);
  expect(shouldAutoGenerateDailyReading({ ...ready, autoGenerateEnabled: false })).toBe(false);
  expect(shouldAutoGenerateDailyReading({ ...ready, isVisible: false })).toBe(false);
  expect(shouldAutoGenerateDailyReading({ ...ready, releaseIsDue: false })).toBe(false);
  expect(shouldAutoGenerateDailyReading({ ...ready, hasScheduledReading: true })).toBe(false);
  expect(shouldAutoGenerateDailyReading({ ...ready, hasBlockingAttempt: true })).toBe(false);
 });

 it("formats the remaining release time without dropping a partial minute", () => {
  expect(formatDailyReadingCountdown(3_600_001)).toBe("01:01");
  expect(formatDailyReadingCountdown(0)).toBe("00:00");
 });
});
