"use client";

import { useEffect, useMemo, useState } from "react";

import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

import type {
 EditAdapter,
 EditFieldDefinition,
 EditFieldKind,
} from "../../adapters/types";

export type StructuredNodeFormProps = {
 value: unknown;
 adapter: EditAdapter;
 formId: string;
 onSubmit: (value: unknown) => void;
 onValidityChange?: (valid: boolean) => void;
 onDraftChange?: (value: unknown) => void;
};

type FormFieldDefinition = EditFieldDefinition & {
 autoGenerated?: boolean;
};

function asEditableRecord(value: unknown): { [key: string]: unknown } {
 return value && typeof value === "object" && !Array.isArray(value)
  ? { ...value }
  : {};
}

function getAutoFieldKind(value: unknown): EditFieldKind {
 if (typeof value === "number") return "number";
 if (typeof value === "boolean") return "boolean";
 if (Array.isArray(value) && value.every((item) => typeof item === "string")) {
  return "string-list";
 }
 if (
  value &&
  (typeof value === "object" || Array.isArray(value))
 ) {
  return "json";
 }
 return "textarea";
}

function valueToFormString(value: unknown, kind: EditFieldKind | undefined) {
 if (kind === "string-list") {
  return Array.isArray(value)
   ? value.filter((item): item is string => typeof item === "string").join("\n")
   : "";
 }

 if (kind === "json") {
  return JSON.stringify(value ?? null, null, 2);
 }

 if (kind === "boolean") {
  return typeof value === "boolean" ? String(value) : "false";
 }

 if (value === null || value === undefined) return "";
 return typeof value === "string" || typeof value === "number"
  ? String(value)
  : JSON.stringify(value, null, 2);
}

function parseFieldValue(
 rawValue: string,
 kind: EditFieldKind | undefined,
 fallback: unknown,
) {
 if (kind === "string-list") {
  return rawValue
   .split("\n")
   .map((item) => item.trim())
   .filter(Boolean);
 }

 if (kind === "number") {
  const parsed = Number(rawValue);
  return Number.isFinite(parsed) ? parsed : fallback;
 }

 if (kind === "boolean") {
  return rawValue === "true";
 }

 if (kind === "json") {
  return JSON.parse(rawValue);
 }

 return rawValue;
}

function buildAutoFields(
 value: unknown,
 adapterFields: EditFieldDefinition[],
): FormFieldDefinition[] {
 const record = asEditableRecord(value);
 const declaredKeys = new Set(adapterFields.map((field) => field.key));

 return Object.entries(record)
  .filter(([key]) => !declaredKeys.has(key))
  .map(([key, fieldValue]) => {
   const kind = getAutoFieldKind(fieldValue);
   return {
    key,
    label: key,
    kind,
    autoGenerated: true,
    description:
     kind === "json"
      ? "Field nested/array: chỉnh JSON của field này."
      : undefined,
   };
  });
}

function buildAutoValues(
 value: unknown,
 fields: FormFieldDefinition[],
): Record<string, string> {
 const record = asEditableRecord(value);
 return Object.fromEntries(
  fields.map((field) => [
   field.key,
   valueToFormString(record[field.key], field.kind),
  ]),
 );
}

function getJsonErrors(
 fields: FormFieldDefinition[],
 values: Record<string, string>,
) {
 return fields.filter((field) => {
  if (field.kind !== "json") return false;

  try {
   JSON.parse(values[field.key] ?? "null");
   return false;
  } catch {
   return true;
  }
 });
}

function applyAutoFields(
 baseNode: unknown,
 original: unknown,
 fields: FormFieldDefinition[],
 values: Record<string, string>,
) {
 const output = asEditableRecord(baseNode);
 const originalRecord = asEditableRecord(original);

 for (const field of fields) {
  output[field.key] = parseFieldValue(
   values[field.key] ?? "",
   field.kind,
   originalRecord[field.key],
  );
 }

 return output;
}

export function StructuredNodeForm({
 value,
 adapter,
 formId,
 onSubmit,
 onValidityChange,
 onDraftChange,
}: StructuredNodeFormProps) {
 const autoFields = useMemo(
  () => buildAutoFields(value, adapter.fields),
  [adapter.fields, value],
 );
 const fields = useMemo<FormFieldDefinition[]>(
  () => [...adapter.fields, ...autoFields],
  [adapter.fields, autoFields],
 );
 const initialValues = useMemo(
  () => ({
   ...buildAutoValues(value, fields),
   ...adapter.toValues(value),
  }),
  [adapter, fields, value],
 );
 const [values, setValues] = useState(initialValues);
 const invalidFields = adapter.fields.filter(
  (field) => field.required && !(values[field.key] ?? "").trim(),
 );
 const jsonErrorFields = getJsonErrors(fields, values);
 const hasValidationError =
  invalidFields.length > 0 || jsonErrorFields.length > 0;

 const buildNode = (nextValues: Record<string, string>) => {
  const autoAppliedNode = applyAutoFields(
   value,
   value,
   autoFields,
   nextValues,
  );

  return adapter.toNode(autoAppliedNode, nextValues);
 };

 useEffect(() => {
  onValidityChange?.(!hasValidationError);
 }, [hasValidationError, onValidityChange]);

 const updateValue = (key: string, nextValue: string) => {
  setValues((current) => {
   const next = { ...current, [key]: nextValue };
   onValidityChange?.(
    adapter.fields.every(
     (field) => !field.required || Boolean((next[field.key] ?? "").trim()),
    ) && getJsonErrors(fields, next).length === 0,
   );
   if (getJsonErrors(fields, next).length === 0) {
    onDraftChange?.(buildNode(next));
   }
   return next;
  });
 };

 return (
  <form
   id={formId}
   className="grid gap-4"
  onSubmit={(event) => {
   event.preventDefault();
   if (hasValidationError) return;
   onSubmit(buildNode(values));
  }}
 >
   {fields.map((field) => {
    const inputId = `${formId}-${field.key}`;
    const fieldValue = values[field.key] ?? "";
    const hasError = Boolean(
     field.required && invalidFields.some((item) => item.key === field.key),
    );
    const hasJsonError = jsonErrorFields.some((item) => item.key === field.key);

    return (
     <label key={field.key} htmlFor={inputId} className="grid gap-1.5">
      <span className="text-sm font-black text-text-primary">
       {field.label}
       {field.required ? " *" : ""}
      </span>
      {field.description ? (
       <span className="text-xs font-semibold text-text-muted">
        {field.description}
       </span>
      ) : null}
      {field.kind === "textarea" ||
      field.kind === "string-list" ||
      field.kind === "json" ? (
       <Textarea
        id={inputId}
        value={fieldValue}
        aria-invalid={hasError || hasJsonError}
        className={field.kind === "json" ? "min-h-40 font-mono text-xs" : "min-h-24"}
        onChange={(event) => updateValue(field.key, event.target.value)}
       />
      ) : field.kind === "boolean" ? (
       <select
        id={inputId}
        value={fieldValue}
        aria-invalid={hasError}
        className="h-10 rounded-lg border border-border-default bg-bg-primary px-3 text-sm font-semibold text-text-primary"
        onChange={(event) => updateValue(field.key, event.target.value)}
       >
        <option value="true">true</option>
        <option value="false">false</option>
       </select>
      ) : (
       <Input
        id={inputId}
        value={fieldValue}
        type={field.kind === "number" ? "number" : "text"}
        aria-invalid={hasError}
        onChange={(event) => updateValue(field.key, event.target.value)}
       />
      )}
      {field.kind === "string-list" ? (
       <span className="text-xs font-semibold text-text-muted">
        Mỗi dòng là một giá trị.
       </span>
      ) : null}
      {hasError ? (
       <span className="text-xs font-bold text-danger-text">
        Trường này không được để trống.
       </span>
      ) : null}
      {hasJsonError ? (
       <span className="text-xs font-bold text-danger-text">
        JSON của field này chưa hợp lệ.
       </span>
      ) : null}
     </label>
    );
   })}
  </form>
 );
}
